### ISSUE TITLE
Using API on google appengine server

### ISSUE THREAD

**Issue by dgreat91** [GideonLeGrange/mikrotik-java#28]
Hi. While this issue might have been previously discussed and solved, i can't seem to find the issue in which it was discussed. Sorry if i am repeating. I'm connecting to a router os running in virtual machine on my pc from a locally deployed google appengine server. But i keep getting 'Connection Refused' error. Please what is the proper way of setting it up? Thank you.

**Comment by GideonLeGrange** [comment]
Hello 

If you’re getting connection refused, it is because the API is not enabled on your router. You need to enable API access on the router using Winbox or the command line. 

Check out this page for more information: http://wiki.mikrotik.com/wiki/Manual:IP/Services <http://wiki.mikrotik.com/wiki/Manual:IP/Services>

Kind regards
Gideon

**Comment by dgreat91** [comment]
Thanks for the reply. But API service is already enabled and accessible with PHP Code. I only get this error if i'm connecting with jsp web application on google appengine. Please if you can, let me know if there is anything i need to do in order for it to work. 

Thanks and Best regards.
Anas

**Comment by GideonLeGrange** [comment]
I guess it could be your JSP security settings. I know some web services containers require security policies to be adjusted to allow network connections from the application. That is not my area of expertise. 

Do the java examples I provide with the library work? Have you tried them?

Gideon

**Comment by dgreat91** [comment]
Okay, Thank you. I will try using the examples.
