### ISSUE TITLE
Encrypted connection

### ISSUE THREAD

**Issue by Metori** [GideonLeGrange/mikrotik-java#30]
I use this API implementation in my android Mikrotik config tool. And it seems that Google restricted use of anonymous TLS in Android 6.
Is there any workaround for this? Or, Gideon, Do you have plans to implement encrypted connection with certificates?

Thanks.

**Comment by GideonLeGrange** [comment]
I wasn't planning encryption with certificates unless people said they don't want anon-TLS. I guess it is now time to look at the certificates. I'll check it out as soon as I have a moment, hopefully later this week.

**Comment by Metori** [comment]
Great. I'll wait for this moment. Thanks.

**Comment by Metori** [comment]
What about this enhancement? ;)

**Comment by Metori** [comment]
Hey, hey, hey... =)

**Comment by Metori** [comment]
Yo, yo

**Comment by GideonLeGrange** [comment]
I'm working on this. I consulted with somebody who knows more about SSL/TLS in Java than me, and he suggested a path that could put the full control of the encryption in the hands of the developer. I'm trying that out, and if I get something useful going, I will update this issue.

**Comment by GideonLeGrange** [comment]
@Metori I have changed the way TLS support works so that I can support certificate-based TLS. There is a branch called `tls` which contains what I am working on. This code builds and the `ConnectTLSCertificate` example works. I connect to a RB750 running 6.33.3 using a self-signed certificte which I have imported into the Java keystore. 

Can you please clone that branch, build it, and see if it works for you. 

Things you will need to read: 
* To setup certificates on Mikrotik: http://blog.a2o.si/2015/08/11/mikrotik-how-to-generate-ssl-certificate-and-enable-https/comment-page-1/#comment-167160
* To import self-signed certificates into a Java keystore: https://docs.oracle.com/javase/tutorial/security/toolsign/rstep2.html

I have no idea how this will work on Android, with regards to certificates. 

Please give me feedback.

**Comment by GideonLeGrange** [comment]
@Metor Take a look at the following two examples:
* how to connect via TLS when using certificates - [ConnectTLSCertificate.java](https://github.com/GideonLeGrange/mikrotik-java/blob/tls/src/main/java/examples/ConnectTLSCertificate.java)
* how to connect with anonymous TLS - [ConnectTLSAnonymous.java](https://github.com/GideonLeGrange/mikrotik-java/blob/tls/src/main/java/examples/ConnectTLSAnonymous.java) and [AnonymousSocketFactory.java](https://github.com/GideonLeGrange/mikrotik-java/blob/tls/src/main/java/examples/AnonymousSocketFactory.java)

**Comment by Metori** [comment]
Yeah. It works. And it works on Android too. Out of the box. Great.

**Comment by ambroseahurra** [comment]
@Metori Please share abit more on how you imported the certs from the mikrotik do you have any solution that doesnot involve doing it manually per device!!!
