### ISSUE TITLE
Unknown Parameter for command " file print where name~"hotspot/img/"" 

### ISSUE THREAD

**Issue by abbasalim** [GideonLeGrange/mikrotik-java#42]
hello
this work in android
List<Map<String, String>> results = con.execute("/file/print  where name=hotspot/img");
but this dont work
List<Map<String, String>> results = con.execute("/file/print  where name~hotspot/img");
how must i do it?

**Comment by GideonLeGrange** [comment]
Hello 

Unfortunately “~” is not supported. This is due to Mikrotik refusing to support it in the underlying RouterOS API, not because I don’t want to support it. 

Please check out this thread for more information: http://forum.mikrotik.com/viewtopic.php?f=9&t=56809 <http://forum.mikrotik.com/viewtopic.php?f=9&t=56809>

Kind regards
Gideon

**Comment by abbasalim** [comment]
but I want to get file list from mikrotik in android! what mus i do it ?

**Comment by GideonLeGrange** [comment]
@abbasalim  What you can do is to retrieve the whole list using `/file/print` without a where and use a Java regular expression to filter them in your code.
