### ISSUE TITLE
MikrotikApiException Messages

### ISSUE THREAD

**Issue by etiennesw** [GideonLeGrange/mikrotik-java#53]
Hi, 

I am using this API well for a couple of month now and all is working great.

The only problem I have is when users fail to connect due to a bad user name or password, the MikrotikApiException message is always "cannot log in".

Is there a way to get more details such as bad password or invalid user?

Also, where can I find a list of messages for MikrotikApiException?

Thanks for your support.

Rgs
Etienne

**Comment by GideonLeGrange** [comment]
Hi Etienne 

The ‘cannot log in’ message is what RouterOS sends back to the API. The router does not tell us if it is the username or password that is wrong. 

There is no list of error messages for MikrotikApiException. This is because the error message for this exception is the one we receive from the router itself. It can therefore be anything that RouterOS wishes to send back to you. 

Kind regards
Gideon

**Comment by etiennesw** [comment]
Understood.

Thanks Gideon for your hard work.

Kind Regards
Etienne
