### ISSUE TITLE
Unknown parameter on regular expression

### ISSUE THREAD

**Issue by ambroseahurra** [GideonLeGrange/mikrotik-java#54]
hey Gideon
Trying to add a layer7 protocol but the regular expression throws unknown parameter error...

<<<Command>>>>
       List<Map<String, String>> e = con.execute("/ip/firewall/layer7-protocol/add regexp="+reg+"");
reg="^(\\x13bittorrent protocol|azver\\x01\$|get /scrape\\\?info_hash=get /announce\\\?info_hash=|get /client/bitcomet/|GET data\\\?fid=)|d1:ad2:id20:|\\x08'7P\\)[RP]"

**Comment by GideonLeGrange** [comment]
Try quoting the value in reg. It contains a space so unless you quote it, it considers the next parameter to start at protocol

**Comment by ambroseahurra** [comment]
Have tried this but still no luck 
now shows:
failure: bad regexp: unmatched ()

String f="\"^(\\\\x13bittorrentprotocol|azver\\\\x01\\$|get/scrape\\\\\\?info_hash=get/announce\\\\\\?info_hash=|get/client/bitcomet/|GET/data\\\\\\?fid=)|d1:ad2:id20:|\\\\x08'7P\\\\)[RP]\"";
       con.execute("/ip/firewall/layer7-protocol/add name=lp regexp="+f+"");

**Comment by ambroseahurra** [comment]
NB: i escaped the inner double quote on the f variable

**Comment by GideonLeGrange** [comment]
The code above is not even valid Java. I'm not sure if it is because your code is wrong or if Github is messing it up. Please post your code inside a code block (Google search for GitHub Markdown if you don't know the syntax) so I can read it. 

Example:
```java
String f="^(\\x13bittorrentprotocol|azver\\x01\$|get/scrape\\\?info_hash=get/announce\\\?info_hash=|get/client/bitcomet/|GET/data\\\?fid=)|d1:ad2:id20:|\\x08'7P\\)[RP]"";
con.execute("/ip/firewall/layer7-protocol/add name=lp regexp="+f+"");
```

Another suggestion: When building regular expressions, use a tool like [RegexPlanet](http://www.regexplanet.com/advanced/java/index.html) to test your expressions. It can also generate the Java code for the expression for you which helps with the escaping.

**Comment by ambroseahurra** [comment]
Thanks Gideon for the heads up on Regex planet, it helped me edit the regular expression. :).. no errors now.
Updated code
```java 
String matcher ="\"^(\\\\x13bittorrent protocol|azver\\\\x01\\$|get /scrape\\\\\\?info_hash=get /announce\\\\\\?info_hash=|get /client/bitcomet/|GET /data\\\\\\?fid=)|d1:ad2:id20:|\\\\x08'7P\\\\[RP]\"";
con.execute("/ip/firewall/layer7-protocol/add name=torrent comment=torrents regexp="+matcher+"");

```

**Comment by GideonLeGrange** [comment]
Glad it is resolved!
